# Generated by Django 4.2.7 on 2023-12-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0009_pdf_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('rank', models.CharField(max_length=255)),
                ('picture', models.ImageField(upload_to='lecturer/')),
            ],
        ),
    ]
