# Generated by Django 4.2.7 on 2023-12-11 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0014_courselecturer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseLecturer',
        ),
    ]
