# Generated by Django 4.2.7 on 2023-12-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0016_rename_pdf_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='associated_lectutrers',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='credit_load',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
