# Generated by Django 4.2.7 on 2023-11-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf',
            old_name='user',
            new_name='course_lecturer',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='pdf',
            name='course_code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdf',
            name='course_title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
