# Generated by Django 4.2.7 on 2023-12-11 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0012_technical'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nonacedemic',
            new_name='AdministrativeStaff',
        ),
    ]
