# Generated by Django 4.2.7 on 2023-12-11 12:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department', '0015_delete_courselecturer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pdf',
            new_name='Course',
        ),
    ]
